language: scala
branches:
  except:
  - release
sudo: true
jdk:
- oraclejdk8
before_cache:
- find $HOME/.ivy2 -name "ivydata-*.properties" -delete
- find $HOME/.sbt -name "*.lock" -delete
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"
script:
 - "./build/build.sh"
